name: BetterWorldStats
version: ${project.version}
main: me.xginko.betterworldstats.BetterWorldStats
authors: [ xGinko ]
softdepend: [ PlaceholderAPI ]
description: ${project.description}
website: ${project.url}
folia-supported: true
api-version: '1.13'

commands:
  betterworldstats:
    description: plugin commands
    usage: /<command> [ reload | version ]
    aliases:
      - betterws
      - bws
  worldstats:
    description: Shows the Statistics
    usage: /<command>
    aliases:
      - stats
permissions:
  betterworldstats.worldstats:
    description: Permission to use /worldstats
    default: true
  betterworldstats.version:
    description: Permission to show the plugin version
  betterworldstats.reload:
    description: Permission to reload the plugin configuration