name: Build and upload jar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build test --stacktrace --scan

      - name: Upload Build
        uses: actions/upload-artifact@v3.1.3
        with:
          name: BetterWorldStats
          path: build/libs/BetterWorldStats*.jar
          if-no-files-found: error